SiteMonitor.Web/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using SiteMonitor.Domain.Models;
using SiteMonitor.Services;
using SiteMonitor.Web.ViewModels;
using Syncfusion.JavaScript;

namespace SiteMonitor.Web.Controllers
{

    [Authorize(Roles = "admin")]
    public class AdminController : Controller
    {
        private readonly IPriceChangeService _priceChangeService;
        private readonly ISiteService _siteService;
        //private readonly ISiteRepository _siteRepository;
        private readonly IMapper _mapper;

        private readonly ILogger<AdminController> _logger;

        public AdminController(IPriceChangeService priceChangeService, ISiteService _siteService, IMapper mapper, ILogger<AdminController> logger)
        {
            this._priceChangeService = priceChangeService;
            this._siteService = _siteService;
            this._logger = logger;
            _mapper = mapper;
        }
        // GET: Admin
        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public ActionResult AddPriceChange()
        {
            try
            {
                var grades = _priceChangeService.GetGrades();

                AddPriceChangeViewModel viewModel = new AddPriceChangeViewModel()
                {
                    Grades = _mapper.Map<List<GradePriceViewModel>>(grades)
                };

                return View(viewModel);
            }
            catch(SqlException ex)
            {
                _logger.LogError(ex, "Error connecting to database.");
                throw (ex);
            }
            catch(Exception ex)
            {
                _logger.LogError(ex, "Error.");
                throw (ex);
            }
            
        }

        [HttpPost]
        public ActionResult AddPriceChange(AddPriceChangeViewModel model)
        {
            if (ModelState.IsValid) {
                List<PriceChange> prices = new List<PriceChange>();
                for (int i = 0; i < model.Grades.Count; ++i)
                {
                    PriceChange priceChange = new PriceChange();
                    priceChange.ChangesOn = model.ChangesOn;
                    priceChange.ScheduledBy = User.Identity.Name;
                    priceChange.ScheduledOn = DateTime.Now;
                    priceChange.IsPending = true;
                    priceChange.GradeId = model.Grades[i].Id;
                    priceChange.Price = model.Grades[i].Price;
                    prices.Add(priceChange);
                    
                }

                try
                {
                    _priceChangeService.AddPriceChanges(prices);

                    //ViewBag.Success = "True";
                    //TempData["message"] = "True";
                    _logger.LogInformation("PriceChange created", prices);
                    TempData["mensaje"] = "exito";

                }
                catch (SqlException ex)
                {
                    _logger.LogError("Error connecting to database.{0}", ex);
                    TempData["mensaje"] = "error";
                    throw (ex);
                }
                catch (Exception ex)
                {
                    _logger.LogError(ex, "Error.");
                    TempData["mensaje"] = "error";
                    throw (ex);
                }

                return RedirectToAction(nameof(AddPriceChange));
            }
            return View(model);
            
        }


        public IActionResult UrlDatasource([FromBody]Data dm)
        {
            //List<Site> a = _siteService.GetActiveSites(onlyActiveSites: false);

            //IEnumerable<int> enumerable = Enumerable.Range(1, 300);
            IEnumerable<Site> order = _siteService.GetActiveSites(onlyActiveSites: false);
            List<Site> Data = order.ToList();

            
            //var Data = order.ToList();
            int count = order.Count();
            return dm.requiresCounts ? Json(new { result = Data.Skip(dm.skip).Take(dm.take), count = count }) : Json(Data);

            //var order = _siteService.GetActiveSites(onlyActiveSites: false).ToList();
            //var Data = order.ToList();
            //int count = order.Count();

            //return Json(new { result = Data, count = count });
        }

       
        //[HttpGet]
        public ActionResult SitesAdministration()
        {
            
            List<Site> sites = null;
            
            try
            {
                sites = _siteService.GetActiveSites(onlyActiveSites: false).ToList();
            }
            catch(SqlException ex)
            {
                _logger.LogError(ex, "Error connecting to database.");
                throw (ex);
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Error. {0}");
                throw (ex);
            }

            ViewBag.DataSource = sites;

            return View();
        }

        [HttpGet]
        public async Task<IActionResult> EditSite(int siteId)
        {

            Site site;

            try
            {
                site = await _siteService.GetSiteAsync(siteId);
            }
            catch(SqlException ex)
            {
                _logger.LogError(ex, "Error connecting to database.");
                throw (ex);
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Error.");
                throw (ex);
            }


            if (site == null)
            {
                return NotFound();
            }
            return View(site);
        }

        [HttpPost]
        public async Task<IActionResult> EditSite(int id, [Bind("Id,Number,Name,IsActive,ReceivesPriceChanges")] Site site)
        {
            if (id != site.Id)
            {
                return NotFound();
            }

            try
            {
                if (ModelState.IsValid)
                {
                    if (site.Name.Length > 0)
                    {
                        await _siteService.UpdateSite(site);
                        _logger.LogInformation("PriceChange created", site);
                    }
                    return RedirectToAction(nameof(SitesAdministration));

                }
            }
            catch (SqlException ex)
            {
                _logger.LogError(ex, "Error connecting to database.");
                throw (ex);
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Error.");
                throw (ex);
            }

            return View(site);

        }

        public ActionResult Update([FromBody]CRUDModel<Site> value)
        {
            _siteService.UpdateSite(value.Value);
            return Json(value.Value);
        }

        //public ActionResult CrudUpdate([FromBody]Site value, string action)
        //{
        //    if (action == "update")
        //    {
        //        //Update record in database
        //        _siteService.UpdateSite(value);
        //    }
        

        public class Data
        {
            public bool requiresCounts { get; set; }
            public int skip { get; set; }
            public int take { get; set; }
        }
    }
}

SiteMonitor.Web/Controllers/LicenceController.cs
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using SiteMonitor.Services;
using SiteMonitor.Web.ViewModels;
using System;
using System.Collections.Generic;
using System.Data.SqlClient;





namespace SiteMonitor.Web.Controllers
{

    public class LicenceController : Controller
    {
        private readonly IMapper _mapper;
        private readonly ILicenceService _licenceService;
        private readonly ISiteService _siteService;
        private readonly ILogger<LicenceController> _logger;

        public LicenceController(IMapper mapper,ILicenceService licenceService,ISiteService siteService, ILogger<LicenceController> logger)
        {
            _mapper = mapper;
            _licenceService = licenceService;
            _siteService = siteService;
            _logger = logger;
        }

        /*public LicenceController(ILicenceService licenceService)
        {
           
            _licenceService = licenceService;
         
        }*/

      
        [Authorize]
        // GET: Licence
        public IActionResult Index()
        {
            try
            {
                var states = _licenceService.GetLicenceStates(includeSiteInfo: true);
                var vm = _mapper.Map<List<LicenceStateViewModel>>(states);

                ViewBag.DataSource1 = vm;

                
            }
            catch (SqlException ex)
            {
                _logger.LogError(ex, "Error connecting to database");
                throw (ex);
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Error");
                throw (ex);
            }


            return View();
        }
    }
}

SiteMonitor.Web/Controllers/PriceChangeController.cs
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using SiteMonitor.Services;
using System;
using System.Data.SqlClient;

namespace SiteMonitor.Web.Controllers
{

    public class PriceChangeController : Controller
    {
        private readonly IMapper _mapper;
        private readonly IPriceChangeService _priceChangeService;
        private readonly ILogger<PriceChangeController> _logger;

        public PriceChangeController(IMapper mapper,IPriceChangeService priceChangeService, ILogger<PriceChangeController> logger)
        {
            _mapper = mapper;
            _priceChangeService = priceChangeService;
            _logger = logger;
        }

        [Authorize]
        // GET: PriceChange
        public ActionResult Index()
        {
            try
            {
                var data2 = _priceChangeService.GetJose(includeGradeInfo: true);
                var data = _priceChangeService.GetScheduledPricesForAllSites(includeGradeInfo: true);
                ViewBag.DataSource = data2;
            }
            catch (SqlException ex)
            {
                _logger.LogError("Error connecting to database. {0}", ex);
                throw (ex);
            }
            catch (Exception ex)
            {
                _logger.LogError("Error. {0}", ex);
                throw (ex);
            }

            return View();
        }

        public ActionResult SchedulePriceChange() {

            return View();
        }
    }
}

SiteMonitor.Web/Views/Shared/_Footer.cshtml
<!-- PAGE FOOTER -->
<div class="page-footer">
    <div class="col-md-12 txt-color-white">
        <p>&copy; @DateTime.Now.Year - GasPro SiteMonitor</p>
    </div>
</div>
<!-- END PAGE FOOTER -->

SiteMonitor.Web/Views/Shared/_Header.cshtml
<!-- HEADER -->
<header id="header">
    <div id="logo-group">
        <!-- PLACE YOUR LOGO HERE -->
        <span id="logo" class="navbar-left">
            <a href="/">
                <img src="~/images/logoGasPro.png" style="max-width:45px; margin-top: -10px; margin-left: 40px;
    margin-bottom: 10px;"  alt="GasPRO" >
            </a>
        </span>


        <!-- END LOGO PLACEHOLDER -->
        <!-- Note: The activity badge color changes when clicked and resets the number to 0
    Suggestion: You may want to set a flag when this happens to tick off all checked messages / notifications -->
        <span id="activity" class="activity-dropdown">
            <i class="fa fa-user"></i> <b class="badge"> 21 </b>
        </span>

        <!-- AJAX-DROPDOWN : control this dropdown height, look and feel from the LESS variable file -->
        <div class="ajax-dropdown">

            <!-- the ID links are fetched via AJAX to the ajax container "ajax-notifications" -->
            <div class="btn-group btn-group-justified" data-toggle="buttons">
                <label class="btn btn-default">
                    <input type="radio" name="activity" id="/ajax/notify/mail.html">
                    Msgs (14)
                </label>
                <label class="btn btn-default">
                    <input type="radio" name="activity" id="/ajax/notify/notifications.html">
                    notify (3)
                </label>
                <label class="btn btn-default">
                    <input type="radio" name="activity" id="/ajax/notify/tasks.html">
                    Tasks (4)
                </label>
            </div>

            <!-- notification content -->
            <div class="ajax-notifications custom-scroll">

                <div class="alert alert-transparent">
                    <h4>Click a button to show messages here</h4>
                    This blank page message helps protect your privacy, or you can show the first message here automatically.
                </div>

                <i class="fa fa-lock fa-4x fa-border"></i>

            </div>
            <!-- end notification content -->
            <!-- footer: refresh area -->
            <span>
                Last updated on: 12/12/2013 9:43AM
                <button type="button" data-loading-text="<i class='fa fa-refresh fa-spin'></i> Loading..." class="btn btn-xs btn-default pull-right">
                    <i class="fa fa-refresh"></i>
                </button>
            </span>
            <!-- end footer -->

        </div>
        <!-- END AJAX-DROPDOWN -->
    </div>

  
    <!-- pulled right: nav area -->
    <div class="pull-right">

        <!-- collapse menu button -->
        <div id="hide-menu" class="btn-header pull-right">
            <span>
                <a href="javascript:void(0);" data-action="toggleMenu" title="Collapse Menu">
                    <i class="fa fa-reorder"></i>
                </a>
            </span>
        </div>
        <!-- end collapse menu -->
        <!-- #MOBILE -->
        <!-- Top menu profile link : this shows only when top menu is active -->
        <ul id="mobile-profile-img" class="header-dropdown-list hidden-xs padding-5">
            <li class="">
                <a href="#" class="dropdown-toggle no-margin userdropdown" data-toggle="dropdown">
                    <img src="~/img/avatars/sunny.png" alt="John Doe" class="online" />
                </a>
                <ul class="dropdown-menu pull-right">
                    <li>
                        <a href="javascript:void(0);" class="padding-10 padding-top-0 padding-bottom-0"><i class="fa fa-cog"></i> Setting</a>
                    </li>
                    <li class="divider"></li>
                    <li>
                        <a asp-controller="AppViews" asp-action="Profile" class="padding-10 padding-top-0 padding-bottom-0"> <i class="fa fa-user"></i> <u>P</u>rofile</a>
                    </li>
                    <li class="divider"></li>
                    <li>
                        <a href="javascript:void(0);" class="padding-10 padding-top-0 padding-bottom-0" data-action="toggleShortcut"><i class="fa fa-arrow-down"></i> <u>S</u>hortcut</a>
                    </li>
                    <li class="divider"></li>
                    <li>
                        <a href="javascript:void(0);" class="padding-10 padding-top-0 padding-bottom-0" data-action="launchFullscreen"><i class="fa fa-arrows-alt"></i> Full <u>S</u>creen</a>
                    </li>
                    <li class="divider"></li>
                    <li>
                        <a asp-controller="Account" asp-action="Logout" class="padding-10 padding-top-5 padding-bottom-5" data-action="userLogout">
                            <i class="fa fa-sign-out fa-lg"></i> <strong><u>L</u>ogout</strong>
                        </a>
                    </li>
                </ul>
            </li>
        </ul>

        <!-- logout button -->
        <div id="logout" class="btn-header transparent pull-right">
            <span>
                <a asp-area="" asp-controller="Account" asp-action="Logout"><i class="fa fa-sign-out"></i></a>

                @*<a asp-controller="Account" asp-action="Logout" title="Sign Out" data-action="userLogout" data-logout-msg="You can improve your security further after logging out by closing this opened browser">
                    <i class="fa fa-sign-out"></i>
                </a>*@
            </span>
        </div>
        <!-- end logout button -->
        <!-- search mobile button (this is hidden till mobile view port) -->
        <div id="search-mobile" class="btn-header transparent pull-right">
            <span>
                <a href="javascript:void(0)" title="Search">
                    <i class="fa fa-search"></i>
                </a>
            </span>
        </div>
        <!-- end search mobile button -->
        
        <!-- fullscreen button -->
        <div id="fullscreen" class="btn-header transparent pull-right">
            <span>
                <a href="javascript:void(0);" data-action="launchFullscreen" title="Full Screen">
                    <i class="fa fa-arrows-alt"></i>
                </a>
            </span>
        </div>
        <!-- end fullscreen button -->
    
      

    </div>
    <!-- end pulled right: nav area -->
</header>
<!-- END HEADER -->

SiteMonitor.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - GasPro SiteMonitor</title>

    <link href="~/styles/material.css" rel="stylesheet" />

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />

        <link rel="stylesheet" type="text/css" href="~/SmartAdmin/css/font-awesome.css" />
        <!-- SmartAdmin Styles : Caution! DO NOT change the order -->
        <link rel="stylesheet" type="text/css" href="~/SmartAdmin/css/smartadmin-production-plugins.css" />
        <!-- SmartAdmin Styles : Caution! IE9/IE10 support a limited amount of selectors; use the minified file -->
        <link rel="stylesheet" type="text/css" href="~/SmartAdmin/css/smartadmin-production.css" />
        <!--<link rel="stylesheet" type="text/css" href="~/css/smartadmin-production.min.css"/>-->
        <link rel="stylesheet" type="text/css" href="~/SmartAdmin/css/smartadmin-skins.css" />

        <!-- Demo purpose only: goes with demo.js, you can delete this css when designing your own WebApp -->
        <link rel="stylesheet" type="text/css" href="~/SmartAdmin/css/demo.css" />

        <!-- We recommend you use "site.css" to override SmartAdmin specific styles; this ensures you keep your customization with each SmartAdmin update. -->
        <link rel="stylesheet" href="~/SmartAdmin/css/site.css" />

        <!-- SmartAdmin RTL Support -->
        <link rel="stylesheet" type="text/css" href="~/SmartAdmin/css/smartadmin-rtl.css" />

    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />

        <link rel="stylesheet" type="text/css" href="~/SmartAdmin/css/font-awesome.min.css" />

        <!-- SmartAdmin Styles : Caution! DO NOT change the order -->
        <link rel="stylesheet" type="text/css" href="~/SmartAdmin/css/smartadmin-production-plugins.min.css" asp-append-version="true" />
        <link rel="stylesheet" type="text/css" href="~/SmartAdmin/css/smartadmin-production.min.css" asp-append-version="true" />
        <link rel="stylesheet" type="text/css" href="~/SmartAdmin/css/smartadmin-skins.min.css" asp-append-version="true" />

        <!-- Demo purpose only: goes with demo.js, you can delete this css when designing your own WebApp -->
        <link rel="stylesheet" type="text/css" href="~/SmartAdmin/css/demo.min.css" asp-append-version="true" />

        <!-- We recommend you use "site.css" to override SmartAdmin specific styles; this ensures you keep your customization with each SmartAdmin update. -->
        <link rel="stylesheet" href="~/SmartAdmin/css/site.min.css" asp-append-version="true" />

        <!-- SmartAdmin RTL Support -->
        <link rel="stylesheet" type="text/css" href="~/SmartAdmin/css/smartadmin-rtl.min.css" />


    </environment>

    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>



    <script src=" https://cdn.syncfusion.com/16.1.0.24/js/web/ej.web.all.min.js" type="text/javascript"></script>
    @* Syncfusion Essential JS 2 Styles *@

    @*<link rel="stylesheet" href="https://cdn.syncfusion.com/ej2/bootstrap.css" />*@

    @* Syncfusion Essential JS 2 Scripts *@

    <script src="https://cdn.syncfusion.com/ej2/dist/ej2.min.js"></script>

    <!-- FAVICONS -->
    <link rel="icon" href="~/images/logogasproIcon.ico" type="image/x-icon" />


    <!-- GOOGLE FONT -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans:400italic,700italic,300,400,700" />

    <!-- Specifying a Webpage Icon for Web Clip Ref: https://developer.apple.com/library/ios/documentation/AppleApplications/Reference/SafariWebContent/ConfiguringWebApplications/ConfiguringWebApplications.html -->

    <link rel="apple-touch-icon" href="~/SmartAdmin/img/splash/sptouch-icon-iphone.png" />
    <link rel="apple-touch-icon" sizes="76x76" href="~/SmartAdmin/img/splash/touch-icon-ipad.png" />
    <link rel="apple-touch-icon" sizes="120x120" href="~/SmartAdmin/img/splash/touch-icon-iphone-retina.png" />
    <link rel="apple-touch-icon" sizes="152x152" href="~/SmartAdmin/img/splash/touch-icon-ipad-retina.png" />

    <!-- iOS web-app metas : hides Safari UI Components and Changes Status Bar Appearance -->
    <!-- Startup image for web apps -->
    <link rel="apple-touch-startup-image" href="~/SmartAdmin/img/splash/ipad-landscape.png" media="screen and (min-device-width: 481px) and (max-device-width: 1024px) and (orientation:landscape)" />
    <link rel="apple-touch-startup-image" href="~/SmartAdmin/img/splash/ipad-portrait.png" media="screen and (min-device-width: 481px) and (max-device-width: 1024px) and (orientation:portrait)" />
    <link rel="apple-touch-startup-image" href="~/SmartAdmin/img/splash/iphone.png" media="screen and (max-device-width: 320px)" />
    <meta name="apple-mobile-web-app-capable" content="yes" />
    <meta name="apple-mobile-web-app-status-bar-style" content="black" />

</head>
<body>
    @{ await Html.RenderPartialAsync("_Header"); }
    @{ await Html.RenderPartialAsync("_Navigation"); }


    <!-- MAIN PANEL -->
    <div id="main" role="main">
        @{ await Html.RenderPartialAsync("_Ribbon"); }
        <!-- MAIN CONTENT -->
        <div id="content">
           @*@RenderSection("ChartsSection", required: false)*@
            @RenderBody()
            @*@RenderSection("ControlsSection", required: false)*@
        </div>
        <!-- END MAIN CONTENT -->
    </div>
    <!-- END MAIN PANEL -->


    @{ await Html.RenderPartialAsync("_Footer"); }
    @{ await Html.RenderPartialAsync("_ShortCuts"); }
    @{ await Html.RenderPartialAsync("_Scripts"); }

    @*<environment include="Development">
            <script src="~/lib/jquery/dist/jquery.js"></script>
            <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
            <script src="~/js/site.js" asp-append-version="true"></script>
        </environment>*@

    <environment exclude="Development">
        @*<script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                    asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                    asp-fallback-test="window.jQuery"
                    crossorigin="anonymous"
                    integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
            </script>*@

        <script data-pace-options='{ "restartOnRequestAfter": true }' src="~/SmartAdmin/js/plugin/pace/pace.js"></script>

        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    <script>
        $(function () {
            // DO NOT REMOVE : GLOBAL FUNCTIONS!
            pageSetUp();
        });
    </script>

   
    <ejs-scripts></ejs-scripts>
    @RenderSection("ScriptSection", required: false)
    @RenderSection("Scripts",required:false)

</body>
</html>

SiteMonitor.Web/Views/Shared/_Navigation.cshtml
@*@inject IOptions<SmartSettings> Settings*@
    <!-- Left panel : Navigation area -->
    <!-- Note: This width of the aside area can be adjusted through LESS variables -->
@using System.Security.Claims;


<aside id="left-panel">
    <!-- User info -->
    <div class="login-info">
        <span>
            <!-- User image size is adjusted inside CSS, it should stay as it -->
            <a href="javascript:void(0);" id="show-shortcut" data-action="toggleShortcut">
                @if (User.Identity.IsAuthenticated){
                @*<img src="@((System.Security.Claims.ClaimsIdentity)User.Identity).FindFirst("picture").Value">*@
                <img src="@User.Claims.FirstOrDefault(c => c.Type == "picture")?.Value" alt="me" class="online" />
                <span>@User.Identity.Name</span>
                <i class="fa fa-angle-down"></i>
                    }
            </a>

        </span>
    </div>
    <!-- end user info -->
    <!-- NAVIGATION : This navigation is also responsive-->
    <nav>
        <!--
        NOTE: Notice the gaps after each icon usage <i></i>..
        Please note that these links work a bit different than
        traditional href="" links. See documentation for details.
        -->

        <ul>
            <li is-active-route asp-controller="Home" asp-action="Index">
                <a asp-controller="Home" asp-action="Index" title="Dashboard">
                    <i class="fa fa-lg fa-fw fa-home"></i> <span class="menu-item-parent">Inicio</span>
                </a>
            </li>
            <li is-active-route asp-controller="Licence" asp-action="Index">
                <a asp-controller="Licence" asp-action="Index" title="Dashboard">
                    <i class="fa fa-lg fa-fw fa-handshake-o"></i> <span class="menu-item-parent">Licencias</span>
                </a>
            </li>
            <li is-active-route asp-controller="PriceChange" asp-action="Index">
                <a asp-controller="PriceChange" asp-action="Index" title="Dashboard">
                    <i class="fa fa-lg fa-fw fa-dollar"></i> <span class="menu-item-parent">Precios</span>
                </a>
            </li>
            @*<li is-active-route asp-controller="Admin" asp-action="AddPriceChange">
                <a asp-controller="PriceChange" asp-action="SchedulePriceChange" title="Cambio de Precios">
                    <i class="fa fa-lg fa-fw fa-exchange"></i> <span class="menu-item-parent">Cambio de Precios</span>
                </a>
            </li>*@

            @if (User.Identity.IsAuthenticated)
                    {
                        if (User.IsInRole("admin")) //if (((System.Security.Claims.ClaimsIdentity)User.Identity).FindFirst("https://josevalverde.example/roles").Value.ToString() == "admin")
                        {
            <li is-active-route asp-controller="Admin">
                <a href="#" title="Dashboard">
                    <i class="fa fa-lg fa-fw fa-unlock"></i> <span class="menu-item-parent">Admin</span>
                </a>
                <ul>
                    <li is-active-route asp-controller="Admin" asp-action="AddPriceChange">
                        <a asp-controller="Admin" asp-action="AddPriceChange" title="Programar Cambio de Precios">
                            <span class="menu-item-parent">Programar Cambio de Precios</span>
                        </a>
                    </li>
                    <li is-active-route asp-controller="Admin" asp-action="SitesAdministration">
                        <a asp-controller="Admin" asp-action="SitesAdministration" title="Modificar Estaciones">
                            <span class="menu-item-parent">Modificar Estaciones</span>
                        </a>
                    </li>

                </ul>
            </li>

                        }
                }

        </ul>
    </nav>
    @*<a asp-controller="Intel" asp-action="Variations" asp-show-when="@Settings.Value.Environment.IsDemo()" class="btn btn-primary nav-demo-btn"><i class="fa fa-info-circle"></i> SmartAdmin Package (187 MB)</a>
        <span class="minifyme" data-action="minifyMenu">
            <i class="fa fa-arrow-circle-left hit"></i>
        </span>*@
    <span class="minifyme" data-action="minifyMenu">
        <i class="fa fa-arrow-circle-left hit"></i>
    </span>
</aside>
    <!-- END NAVIGATION -->

SiteMonitor.Web/Views/Shared/_Ribbon.cshtml
<!-- RIBBON -->
<div id="ribbon">

   

    <!-- breadcrumb -->
    <ol class="breadcrumb">
        <li>Home</li>
        <li>Dashboard</li>
    </ol>
    <!-- end breadcrumb -->
    <!-- You can also add more buttons to the
    ribbon for further usability

    Example below:

    <span class="ribbon-button-alignment pull-right">
        <span id="search" class="btn btn-ribbon hidden-xs" data-title="search"><i class="fa-grid"></i> Change Grid</span>
        <span id="add" class="btn btn-ribbon hidden-xs" data-title="add"><i class="fa-plus"></i> Add</span>
        <span id="search" class="btn btn-ribbon" data-title="search">
            <i class="fa-search"></i> <span class="hidden-mobile">Search</span>
        </span>
    </span> -->

</div>
<!-- END RIBBON -->